#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx pretty-quick --staged
npx eslint --ignore-pattern '.eslintrc.cjs' --fix $(git diff --name-only --diff-filter=ACMRTUXB main | grep -E "(.js$|.jsx$|.ts$|.tsx$)" | xargs)
